// Hitos de la línea de tiempo. Mismo contenido que js/i18n.js de la versión actual.
import type { Lang } from "./i18n";

export type Milestone = { id: string; period: string; title: string; region: string; text: string; book: string; bookTitle: string; chapter: number };

export const milestones: Record<Lang, Milestone[]> = {
  es: [
    {"id": "patriarchs", "period": "Patriarcas", "title": "Abraham sale hacia Canaán", "region": "Mesopotamia · Canaán · Egipto", "text": "La historia de Abraham conecta Ur, Harán, Canaán y las rutas hacia Egipto. El desplazamiento abre el relato de las promesas patriarcales.", "book": "genesis", "bookTitle": "Génesis", "chapter": 12},
    {"id": "exodus", "period": "Éxodo", "title": "Israel sale de Egipto", "region": "Egipto · Mar Rojo · Sinaí", "text": "La salida de Egipto y el camino por el desierto forman el gran eje geográfico del éxodo y preparan la entrada en Canaán.", "book": "exodo", "bookTitle": "Éxodo", "chapter": 12},
    {"id": "conquest", "period": "Conquista", "title": "Entrada y asentamiento en Canaán", "region": "Jordán · Jericó · Canaán", "text": "El cruce del Jordán y la organización del territorio sitúan a Israel en Canaán, con Jerusalén como referencia posterior.", "book": "josue", "bookTitle": "Josué", "chapter": 1},
    {"id": "monarchy", "period": "Monarquía", "title": "Jerusalén se convierte en capital", "region": "Jerusalén · Judá · Israel", "text": "David establece Jerusalén como centro político y espiritual del reino, un punto que marcará la memoria bíblica.", "book": "2-samuel", "bookTitle": "2 Samuel", "chapter": 5},
    {"id": "exile", "period": "Exilio", "title": "Jerusalén cae ante Babilonia", "region": "Judá · Babilonia · Mesopotamia", "text": "La caída de Jerusalén desplaza a comunidades de Judá hacia Babilonia y abre una etapa de pérdida, memoria y esperanza de retorno.", "book": "2-reyes", "bookTitle": "2 Reyes", "chapter": 25},
    {"id": "return", "period": "Retorno", "title": "Regreso y reconstrucción", "region": "Babilonia · Jerusalén · Judá", "text": "El retorno desde Babilonia reactiva la vida comunitaria y la reconstrucción de Jerusalén.", "book": "esdras", "bookTitle": "Esdras", "chapter": 1},
    {"id": "gospels", "period": "Evangelios", "title": "Jesús nace en Judea y recorre Galilea", "region": "Belén · Galilea · Jerusalén", "text": "Los evangelios recorren Galilea, Judea y Jerusalén, conectando aldeas, caminos y la ciudad de los acontecimientos finales.", "book": "mateo", "bookTitle": "Mateo", "chapter": 1},
    {"id": "early-church", "period": "Iglesia primitiva", "title": "El mensaje llega a las naciones", "region": "Jerusalén · Siria · Mediterráneo", "text": "Hechos muestra la expansión del movimiento desde Jerusalén hacia Siria, Asia Menor, Grecia y Roma.", "book": "hechos", "bookTitle": "Hechos", "chapter": 2},
  ],
  en: [
    {"id": "patriarchs", "period": "Patriarchs", "title": "Abraham sets out for Canaan", "region": "Mesopotamia · Canaan · Egypt", "text": "Abraham's story connects Ur, Haran, Canaan and the routes toward Egypt. The journey opens the account of the patriarchal promises.", "book": "genesis", "bookTitle": "Genesis", "chapter": 12},
    {"id": "exodus", "period": "Exodus", "title": "Israel leaves Egypt", "region": "Egypt · Red Sea · Sinai", "text": "The departure from Egypt and the journey through the desert form the great geographic axis of the exodus and prepare the entrance into Canaan.", "book": "exodo", "bookTitle": "Exodus", "chapter": 12},
    {"id": "conquest", "period": "Conquest", "title": "Entry and settlement in Canaan", "region": "Jordan · Jericho · Canaan", "text": "The crossing of the Jordan and the organization of the territory place Israel in Canaan, with Jerusalem as a later reference point.", "book": "josue", "bookTitle": "Joshua", "chapter": 1},
    {"id": "monarchy", "period": "Monarchy", "title": "Jerusalem becomes the capital", "region": "Jerusalem · Judah · Israel", "text": "David establishes Jerusalem as the political and spiritual center of the kingdom, a point that will mark biblical memory.", "book": "2-samuel", "bookTitle": "2 Samuel", "chapter": 5},
    {"id": "exile", "period": "Exile", "title": "Jerusalem falls to Babylon", "region": "Judah · Babylon · Mesopotamia", "text": "The fall of Jerusalem displaces communities from Judah to Babylon and opens a stage of loss, memory and hope of return.", "book": "2-reyes", "bookTitle": "2 Kings", "chapter": 25},
    {"id": "return", "period": "Return", "title": "Return and rebuilding", "region": "Babylon · Jerusalem · Judah", "text": "The return from Babylon revives community life and the rebuilding of Jerusalem.", "book": "esdras", "bookTitle": "Ezra", "chapter": 1},
    {"id": "gospels", "period": "Gospels", "title": "Jesus is born in Judea and travels through Galilee", "region": "Bethlehem · Galilee · Jerusalem", "text": "The Gospels move through Galilee, Judea and Jerusalem, connecting villages, roads and the city of the final events.", "book": "mateo", "bookTitle": "Matthew", "chapter": 1},
    {"id": "early-church", "period": "Early church", "title": "The message reaches the nations", "region": "Jerusalem · Syria · Mediterranean", "text": "Acts shows the movement's expansion from Jerusalem toward Syria, Asia Minor, Greece and Rome.", "book": "hechos", "bookTitle": "Acts", "chapter": 2},
  ],
  de: [
    {"id": "patriarchs", "period": "Patriarchen", "title": "Abraham bricht nach Kanaan auf", "region": "Mesopotamien · Kanaan · Ägypten", "text": "Abrahams Geschichte verbindet Ur, Haran, Kanaan und die Wege nach Ägypten. Der Aufbruch eröffnet die Erzählung der patriarchalischen Verheißungen.", "book": "genesis", "bookTitle": "1. Mose", "chapter": 12},
    {"id": "exodus", "period": "Auszug", "title": "Israel verlässt Ägypten", "region": "Ägypten · Rotes Meer · Sinai", "text": "Der Auszug aus Ägypten und der Weg durch die Wüste bilden die große geografische Achse des Exodus und bereiten den Einzug in Kanaan vor.", "book": "exodo", "bookTitle": "2. Mose", "chapter": 12},
    {"id": "conquest", "period": "Landnahme", "title": "Einzug und Ansiedlung in Kanaan", "region": "Jordan · Jericho · Kanaan", "text": "Die Durchquerung des Jordan und die Gliederung des Gebiets verorten Israel in Kanaan, mit Jerusalem als späterem Bezugspunkt.", "book": "josue", "bookTitle": "Josua", "chapter": 1},
    {"id": "monarchy", "period": "Königszeit", "title": "Jerusalem wird Hauptstadt", "region": "Jerusalem · Juda · Israel", "text": "David macht Jerusalem zum politischen und geistlichen Zentrum des Reiches, ein Punkt, der die biblische Erinnerung prägen wird.", "book": "2-samuel", "bookTitle": "2. Samuel", "chapter": 5},
    {"id": "exile", "period": "Exil", "title": "Jerusalem fällt an Babylon", "region": "Juda · Babylon · Mesopotamien", "text": "Der Fall Jerusalems verdrängt Gemeinschaften aus Juda nach Babylon und eröffnet eine Zeit des Verlusts, der Erinnerung und der Hoffnung auf Rückkehr.", "book": "2-reyes", "bookTitle": "2. Könige", "chapter": 25},
    {"id": "return", "period": "Rückkehr", "title": "Rückkehr und Wiederaufbau", "region": "Babylon · Jerusalem · Juda", "text": "Die Rückkehr aus Babylon belebt das Gemeinschaftsleben und den Wiederaufbau Jerusalems neu.", "book": "esdras", "bookTitle": "Esra", "chapter": 1},
    {"id": "gospels", "period": "Evangelien", "title": "Jesus wird in Judäa geboren und zieht durch Galiläa", "region": "Betlehem · Galiläa · Jerusalem", "text": "Die Evangelien führen durch Galiläa, Judäa und Jerusalem und verbinden Dörfer, Wege und die Stadt der abschließenden Ereignisse.", "book": "mateo", "bookTitle": "Matthäus", "chapter": 1},
    {"id": "early-church", "period": "Frühe Kirche", "title": "Die Botschaft erreicht die Völker", "region": "Jerusalem · Syrien · Mittelmeerraum", "text": "Die Apostelgeschichte zeigt die Ausbreitung der Bewegung von Jerusalem nach Syrien, Kleinasien, Griechenland und Rom.", "book": "hechos", "bookTitle": "Apostelgeschichte", "chapter": 2},
  ],
};
