export const babelCopy = {
  es: {
    metaTitle: 'Babel: ciudad, torre y dispersión | Horizonte 55',
    metaDescription: 'Recorrido guiado de Génesis 11 que distingue el texto sagrado del contexto histórico de Babilonia y los zigurats.',
    hero: ['Contexto bíblico · Segundo piloto editorial', 'Babel: ciudad, torre y dispersión', 'Génesis 11 presenta una ciudad, una torre, un nombre buscado por sus constructores y una dispersión realizada por Dios. Observaremos primero el texto sagrado y después el contexto de Babilonia y de los zigurats.', 'Al terminar:', 'podrás distinguir lo que afirma el texto sagrado, lo que aporta el contexto antiguo y lo que continúa siendo una interpretación.', 'Leer Génesis 11:1–9', 'Volver al capítulo'],
    factsLabel: 'Ficha del estudio',
    facts: [['Pasaje', 'Génesis 11:1–9'], ['Pregunta central', '¿Qué afirma el relato y qué puede aportar el contexto de Babilonia?'], ['Lectura estimada', '9–11 minutos'], ['Estado', 'Piloto interno · versión 0.1']],
    faith: ['Criterio del estudio', 'La Escritura es el fundamento', 'Horizonte 55 recibe el texto sagrado como fundamento de este estudio. La arqueología y la historia pueden iluminar el entorno antiguo, pero no sustituyen el mensaje de la Escritura ni convierten una asociación posible en una identificación comprobada.'],
    observation: {
      heading: ['Primero, mira el texto sagrado', 'Observa antes de reconstruir'],
      prompt: 'Lee Génesis 11:1–9 y sigue el movimiento del relato: ¿qué encuentra la humanidad, qué decide construir, qué busca y qué hace Dios?',
      answerLabel: 'Comparar con una observación guiada', tableLabel: 'Secuencia narrativa de Génesis 11:1–9', headers: ['Elemento', 'Información que proporciona el pasaje'],
      rows: [['Lengua', 'Toda la tierra compartía una lengua y unas mismas palabras.'], ['Lugar', 'Los pobladores encontraron una llanura en la tierra de Sinar y se establecieron allí.'], ['Proyecto', 'Decidieron edificar una ciudad y una torre cuya cúspide llegara al cielo.'], ['Motivo', 'Querían hacerse un nombre y evitar ser dispersados.'], ['Acción de Dios', 'El Señor descendió, confundió su lengua y frustró la comunicación.'], ['Resultado', 'Fueron dispersados sobre la tierra y dejaron de edificar la ciudad.']],
      note: 'El texto sagrado nombra Babel y Sinar, pero no proporciona las dimensiones, la forma ni unas coordenadas modernas para la torre.'
    },
    known: ['Grados de certeza', 'Qué puede reconocerse y qué permanece abierto', 'El contexto antiguo ayuda cuando se mantiene una frontera clara entre el lugar histórico, la arquitectura conocida y el acontecimiento narrado por la Escritura.'],
    certainty: [
      ['Contexto ampliamente reconocido', 'Babel, Babilonia y Sinar', 'Babel se relaciona tradicionalmente con Babilonia, en la llanura de la baja Mesopotamia. Las ruinas de la ciudad histórica se encuentran en el actual Irak.'],
      ['Identificación no comprobada', 'La torre concreta del relato', 'Babilonia tuvo grandes zigurats, incluido Etemenanki, pero la arqueología no demuestra que una estructura conservada sea la torre exacta de Génesis 11.']
    ],
    views: ['Tres lentes complementarias', 'Cómo leer el relato y su contexto', 'Estas tres lentes no compiten por localizar la torre: responden preguntas diferentes y deben conservar distintos grados de certeza.'],
    expand: 'Ampliar imagen', proposal: 'Qué aporta', explain: 'Qué detalles ayuda a comprender', difficulty: 'Qué límite debemos conservar',
    theories: [
      { title: 'Lectura teológica del relato', body: 'Pone en primer plano la soberanía de Dios frente al proyecto humano de concentrarse, hacerse un nombre y evitar la dispersión.', support: 'El motivo declarado por los constructores, la acción de Dios y el desenlace del relato.', limit: 'La interpretación teológica no determina la forma material ni la ubicación exacta de la torre.', source: 'Lecturas relacionadas:', sourceLinks: ['fuente 5', 'fuente 6'], caption: 'Ilustración conceptual de la ambición humana, la intervención divina y la dispersión. No representa una reconstrucción arqueológica.', alt: 'Ilustración en estilo de pergamino de una ciudad y una torre inacabada, bajo una luz celestial, mientras grupos humanos parten hacia distintas direcciones.', aria: 'Ampliar ilustración teológica de Babel y la dispersión' },
      { title: 'Babilonia en la llanura de Mesopotamia', body: 'Sitúa el marco histórico en Babilonia, una antigua ciudad junto al Éufrates dentro de la amplia llanura aluvial de la baja Mesopotamia.', support: 'La localización arqueológica de Babilonia, su paisaje fluvial y su larga tradición urbana.', limit: 'Reconocer Babilonia no identifica automáticamente el edificio ni fecha el acontecimiento de Génesis 11.', source: 'Lecturas relacionadas:', sourceLinks: ['fuente 1', 'fuente 2'], caption: 'Ilustración conceptual de Babilonia y su llanura fluvial. No es un plano arqueológico ni localiza la torre con certeza.', alt: 'Vista conceptual en pergamino de una ciudad de adobe junto al Éufrates, rodeada por canales, campos y palmeras.', aria: 'Ampliar ilustración de Babilonia en la llanura mesopotámica' },
      { title: 'Zigurats y Etemenanki', body: 'Los zigurats muestran cómo las ciudades mesopotámicas levantaban grandes plataformas escalonadas para sus templos. Etemenanki fue el gran zigurat de Babilonia.', support: 'Restos arqueológicos, inscripciones reales y comparaciones con otros zigurats mesopotámicos.', limit: 'Una semejanza cultural o arquitectónica puede ofrecer contexto; no prueba que Etemenanki sea la torre exacta del texto sagrado.', source: 'Lecturas relacionadas:', sourceLinks: ['fuente 2', 'fuente 3', 'fuente 4'], caption: 'Reconstrucción visual conceptual de un zigurat mesopotámico en construcción. No representa la torre de Babel como identificación comprobada.', alt: 'Ilustración en estilo de pergamino de un gran zigurat de adobe en construcción, con rampas, andamios y trabajadores.', aria: 'Ampliar reconstrucción conceptual de un zigurat mesopotámico' }
    ],
    comparison: ['Comparación de lentes', 'Qué responde y qué no responde cada enfoque'], comparisonLabel: 'Tabla comparativa del estudio de Babel',
    headers: ['Enfoque', 'Punto de apoyo', 'Aporte principal', 'Límite'],
    rows: [['Lectura teológica', 'La secuencia y los motivos expresados en Génesis 11.', 'Orienta la atención hacia Dios, la intención humana y la dispersión.', 'No reconstruye un edificio histórico.'], ['Contexto de Babilonia', 'La ciudad histórica y su paisaje en la baja Mesopotamia.', 'Da un marco geográfico y urbano plausible para Sinar y Babel.', 'No demuestra la fecha ni el lugar exactos del acontecimiento.'], ['Contexto de los zigurats', 'Arquitectura, restos e inscripciones de Mesopotamia.', 'Explica qué clase de construcción monumental conoció la región.', 'Etemenanki es un posible trasfondo, no una identificación demostrada.']],
    method: ['Criterio:', 'el texto sagrado, el lugar arqueológico y las propuestas interpretativas se presentan como niveles distintos de evidencia.'],
    conclusion: ['Lo que ya puedes reconocer', 'Qué aporta el contexto al relato de Babel', 'Babel pertenece a un mundo urbano mesopotámico donde las ciudades, el ladrillo y las construcciones escalonadas eran realidades concretas. Ese contexto hace más comprensible la escena, pero no permite señalar una ruina y declarar que es la torre exacta de Génesis 11.', 'El centro del relato permanece en la acción de Dios y en el resultado del proyecto humano. La arqueología ilumina el escenario; el texto sagrado define el mensaje del estudio.'],
    reflection: {
      heading: ['Regresa al texto sagrado', '¿Qué aporta esto a mi lectura?'], answerLabel: 'Ver una respuesta orientativa',
      items: [['1. Distingue motivo e interpretación', '¿Qué motivos atribuye explícitamente Génesis 11:4 a los constructores y qué valoración añadimos al interpretarlos?', 'El versículo expresa el deseo de hacerse un nombre y evitar la dispersión. La lectura de orgullo, autosuficiencia o resistencia al propósito de Dios es una interpretación teológica coherente con la secuencia, pero conviene distinguirla de las palabras explícitas del pasaje.'], ['2. Mira el desenlace', '¿Cómo responde Dios al proyecto y qué cambia en la vida de los constructores?', 'Dios confunde su lengua, interrumpe la comunicación y los dispersa. La ciudad queda inconclusa y la concentración buscada por sus constructores da paso a la distribución de los pueblos.']],
      link: 'Volver a Génesis 11:1–9', takeaway: ['Resultado del recorrido:', 'ahora puedes reconocer el mensaje central del relato, situarlo prudentemente en el mundo mesopotámico y evitar presentar un zigurat conocido como una identificación comprobada de la torre.']
    },
    glossary: ['Palabras clave', 'Glosario breve'], glossaryEntries: [['Babel', 'Nombre de la ciudad en Génesis 11, vinculado en el relato con la confusión de las lenguas.'], ['Sinar', 'Región bíblica asociada habitualmente con Babilonia y la baja Mesopotamia.'], ['Babilonia', 'Antigua ciudad mesopotámica situada junto al Éufrates, en el actual Irak.'], ['Zigurat', 'Construcción mesopotámica de terrazas escalonadas vinculada a un complejo de templo.'], ['Etemenanki', 'Gran zigurat de Babilonia dedicado a Marduk; ofrece contexto histórico, pero no una identificación demostrada de la torre bíblica.']],
    editorial: ['Ficha editorial', 'Alcance y revisión'], editorialEntries: [['Responsable', 'Jose A Bejarano V'], ['Versión', '0.1 · segundo piloto interno trilingüe'], ['Última revisión', '20 de septiembre de 2026'], ['Método', 'Lectura guiada que distingue el texto sagrado, el contexto histórico-arqueológico y las interpretaciones teológicas.']],
    ai: ['Sobre las imágenes:', 'las ilustraciones conceptuales generadas con inteligencia artificial sirven como apoyo visual. No constituyen evidencia histórica, arqueológica o geográfica.'],
    sources: ['Fuentes para continuar', 'Lecturas consultadas'], sourceNotes: ['ficha institucional y datos arqueológicos del sitio de Babilonia.', 'síntesis institucional sobre Etemenanki y sus restos.', 'introducción museística a la arquitectura de los zigurats.', 'inscripción de Nabucodonosor II sobre la reconstrucción de Etemenanki.', 'estudio del trasfondo babilónico del lenguaje en Génesis 11.', 'análisis retórico sobre unidad, dispersión y el orden de la creación.'], close: 'Cerrar imagen ampliada'
  },
  en: {
    metaTitle: 'Babel: city, tower and scattering | Horizonte 55', metaDescription: 'A guided journey through Genesis 11 that distinguishes the sacred text from the historical context of Babylon and ziggurats.',
    hero: ['Biblical context · Second editorial pilot', 'Babel: city, tower and scattering', 'Genesis 11 presents a city, a tower, a name sought by its builders and a scattering carried out by God. We will first observe the sacred text and then the context of Babylon and ziggurats.', 'By the end:', 'you will be able to distinguish what the sacred text affirms, what ancient context contributes and what remains interpretation.', 'Read Genesis 11:1–9', 'Return to the chapter'],
    factsLabel: 'Study overview', facts: [['Passage', 'Genesis 11:1–9'], ['Central question', 'What does the account affirm, and what can Babylonian context contribute?'], ['Estimated reading time', '9–11 minutes'], ['Status', 'Internal pilot · version 0.1']],
    faith: ['Study criterion', 'Scripture is the foundation', 'Horizonte 55 receives the sacred text as the foundation of this study. Archaeology and history can illuminate the ancient setting, but they do not replace Scripture’s message or turn a possible association into a proven identification.'],
    observation: { heading: ['First, look at the sacred text', 'Observe before reconstructing'], prompt: 'Read Genesis 11:1–9 and follow the movement of the account: what does humanity find, decide to build and seek, and what does God do?', answerLabel: 'Compare with a guided observation', tableLabel: 'Narrative sequence of Genesis 11:1–9', headers: ['Element', 'Information provided by the passage'], rows: [['Language', 'The whole earth shared one language and the same words.'], ['Place', 'The people found a plain in the land of Shinar and settled there.'], ['Project', 'They decided to build a city and a tower with its top in the heavens.'], ['Motive', 'They wanted to make a name for themselves and avoid being scattered.'], ['God’s action', 'The Lord came down, confused their language and disrupted communication.'], ['Result', 'They were scattered over the earth and stopped building the city.']], note: 'The sacred text names Babel and Shinar, but it does not provide the tower’s dimensions, shape or modern coordinates.' },
    known: ['Degrees of certainty', 'What can be recognized and what remains open', 'Ancient context helps when we keep a clear boundary between the historical place, known architecture and the event narrated by Scripture.'],
    certainty: [['Widely recognized context', 'Babel, Babylon and Shinar', 'Babel is traditionally associated with Babylon on the plain of Lower Mesopotamia. The ruins of the historical city are in present-day Iraq.'], ['Unproven identification', 'The specific tower in the account', 'Babylon had great ziggurats, including Etemenanki, but archaeology does not demonstrate that a surviving structure is the exact tower of Genesis 11.']],
    views: ['Three complementary lenses', 'How to read the account and its context', 'These lenses do not compete to locate the tower: they answer different questions and require different degrees of certainty.'], expand: 'Enlarge image', proposal: 'What it contributes', explain: 'Which details it helps explain', difficulty: 'Which limit must remain',
    theories: [
      { title: 'Theological reading of the account', body: 'It foregrounds God’s sovereignty over the human project to concentrate, make a name and avoid scattering.', support: 'The builders’ stated motive, God’s action and the outcome of the account.', limit: 'The theological interpretation does not determine the tower’s material form or exact location.', source: 'Related readings:', sourceLinks: ['source 5', 'source 6'], caption: 'Conceptual illustration of human ambition, divine intervention and scattering. It is not an archaeological reconstruction.', alt: 'Parchment-style illustration of an unfinished city and tower under heavenly light while human groups depart in different directions.', aria: 'Enlarge theological illustration of Babel and the scattering' },
      { title: 'Babylon on the Mesopotamian plain', body: 'It places the historical setting in Babylon, an ancient city beside the Euphrates within the broad alluvial plain of Lower Mesopotamia.', support: 'Babylon’s archaeological location, river landscape and long urban tradition.', limit: 'Recognizing Babylon does not automatically identify the building or date the event of Genesis 11.', source: 'Related readings:', sourceLinks: ['source 1', 'source 2'], caption: 'Conceptual illustration of Babylon and its river plain. It is neither an archaeological plan nor a certain location of the tower.', alt: 'Conceptual parchment view of a mud-brick city beside the Euphrates, surrounded by canals, fields and palms.', aria: 'Enlarge illustration of Babylon on the Mesopotamian plain' },
      { title: 'Ziggurats and Etemenanki', body: 'Ziggurats show how Mesopotamian cities raised great stepped platforms for their temples. Etemenanki was Babylon’s great ziggurat.', support: 'Archaeological remains, royal inscriptions and comparisons with other Mesopotamian ziggurats.', limit: 'Cultural or architectural similarity can provide context; it does not prove that Etemenanki is the exact tower in the sacred text.', source: 'Related readings:', sourceLinks: ['source 2', 'source 3', 'source 4'], caption: 'Conceptual visual reconstruction of a Mesopotamian ziggurat under construction. It does not identify the Tower of Babel as proven.', alt: 'Parchment-style illustration of a large mud-brick ziggurat under construction with ramps, scaffolding and workers.', aria: 'Enlarge conceptual reconstruction of a Mesopotamian ziggurat' }
    ],
    comparison: ['Comparison of lenses', 'What each approach answers and leaves unanswered'], comparisonLabel: 'Comparison table for the Babel study', headers: ['Approach', 'Supporting point', 'Main contribution', 'Limit'], rows: [['Theological reading', 'The sequence and expressed motives in Genesis 11.', 'Directs attention to God, human intention and scattering.', 'Does not reconstruct a historical building.'], ['Babylonian context', 'The historical city and its Lower Mesopotamian landscape.', 'Provides a plausible geographical and urban setting for Shinar and Babel.', 'Does not prove the event’s precise date or place.'], ['Ziggurat context', 'Mesopotamian architecture, remains and inscriptions.', 'Explains the kind of monumental building known in the region.', 'Etemenanki is possible background, not a demonstrated identification.']],
    method: ['Criterion:', 'the sacred text, the archaeological place and interpretive proposals are presented as distinct levels of evidence.'],
    conclusion: ['What you can now recognize', 'What context contributes to the Babel account', 'Babel belongs to an urban Mesopotamian world in which cities, bricks and stepped structures were concrete realities. That context makes the scene more understandable, but it does not allow us to point to a ruin and declare it the exact tower of Genesis 11.', 'The centre of the account remains God’s action and the outcome of the human project. Archaeology illuminates the setting; the sacred text defines the study’s message.'],
    reflection: { heading: ['Return to the sacred text', 'What does this add to my reading?'], answerLabel: 'See a guided answer', items: [['1. Distinguish motive and interpretation', 'Which motives does Genesis 11:4 explicitly attribute to the builders, and which evaluation do we add when interpreting them?', 'The verse states the desire to make a name and avoid scattering. Reading pride, self-sufficiency or resistance to God’s purpose is a theological interpretation consistent with the sequence, but it should be distinguished from the passage’s explicit words.'], ['2. Look at the outcome', 'How does God respond to the project, and what changes in the builders’ lives?', 'God confuses their language, interrupts communication and scatters them. The city remains unfinished, and the concentration they sought gives way to the distribution of peoples.']], link: 'Return to Genesis 11:1–9', takeaway: ['Result of the journey:', 'you can now recognize the account’s central message, place it carefully in the Mesopotamian world and avoid presenting a known ziggurat as a proven identification of the tower.'] },
    glossary: ['Key terms', 'Brief glossary'], glossaryEntries: [['Babel', 'The city’s name in Genesis 11, linked in the account with the confusion of languages.'], ['Shinar', 'A biblical region commonly associated with Babylonia and Lower Mesopotamia.'], ['Babylon', 'An ancient Mesopotamian city beside the Euphrates in present-day Iraq.'], ['Ziggurat', 'A Mesopotamian stepped-terrace construction associated with a temple complex.'], ['Etemenanki', 'Babylon’s great ziggurat dedicated to Marduk; it provides historical context but is not a demonstrated identification of the biblical tower.']],
    editorial: ['Editorial record', 'Scope and review'], editorialEntries: [['Responsible person', 'Jose A Bejarano V'], ['Version', '0.1 · second trilingual internal pilot'], ['Last reviewed', '20 September 2026'], ['Method', 'A guided reading that distinguishes the sacred text, historical-archaeological context and theological interpretations.']], ai: ['About the images:', 'the conceptual illustrations generated with artificial intelligence serve as visual support. They are not historical, archaeological or geographical evidence.'],
    sources: ['Sources for further study', 'Works consulted'], sourceNotes: ['institutional record and archaeological data for Babylon.', 'institutional overview of Etemenanki and its remains.', 'museum introduction to ziggurat architecture.', 'Nebuchadnezzar II inscription on rebuilding Etemenanki.', 'study of the Babylonian background of language in Genesis 11.', 'rhetorical analysis of unity, scattering and creation order.'], close: 'Close enlarged image'
  },
  de: {
    metaTitle: 'Babel: Stadt, Turm und Zerstreuung | Horizonte 55', metaDescription: 'Ein geführter Weg durch 1. Mose 11, der die Heilige Schrift vom historischen Kontext Babylons und der Zikkurate unterscheidet.',
    hero: ['Biblischer Kontext · Zweiter redaktioneller Pilot', 'Babel: Stadt, Turm und Zerstreuung', '1. Mose 11 berichtet von einer Stadt, einem Turm, einem Namen, den die Bauleute suchen, und einer Zerstreuung durch Gott. Wir betrachten zuerst die Heilige Schrift und danach den Kontext Babylons und der Zikkurate.', 'Am Ende:', 'kannst du unterscheiden, was die Heilige Schrift aussagt, was der antike Kontext beiträgt und was Auslegung bleibt.', '1. Mose 11,1–9 lesen', 'Zum Kapitel zurückkehren'],
    factsLabel: 'Übersicht zur Studie', facts: [['Bibelstelle', '1. Mose 11,1–9'], ['Leitfrage', 'Was sagt der Bericht aus, und was trägt der babylonische Kontext bei?'], ['Geschätzte Lesezeit', '9–11 Minuten'], ['Status', 'Interner Pilot · Version 0.1']],
    faith: ['Maßstab der Studie', 'Die Heilige Schrift ist die Grundlage', 'Horizonte 55 nimmt die Heilige Schrift als Grundlage dieser Studie. Archäologie und Geschichte können das antike Umfeld erhellen, ersetzen aber weder die Botschaft der Schrift noch machen sie aus einer möglichen Verbindung eine nachgewiesene Zuordnung.'],
    observation: { heading: ['Sieh zuerst auf die Heilige Schrift', 'Beobachte, bevor du rekonstruierst'], prompt: 'Lies 1. Mose 11,1–9 und verfolge den Ablauf: Was findet die Menschheit, was will sie bauen und erreichen, und was tut Gott?', answerLabel: 'Mit einer geführten Beobachtung vergleichen', tableLabel: 'Erzählfolge in 1. Mose 11,1–9', headers: ['Element', 'Angabe im Abschnitt'], rows: [['Sprache', 'Die ganze Erde hatte eine Sprache und dieselben Worte.'], ['Ort', 'Die Menschen fanden eine Ebene im Land Schinar und ließen sich dort nieder.'], ['Vorhaben', 'Sie wollten eine Stadt und einen Turm bauen, dessen Spitze bis an den Himmel reicht.'], ['Motiv', 'Sie wollten sich einen Namen machen und ihre Zerstreuung verhindern.'], ['Gottes Handeln', 'Der Herr kam herab, verwirrte ihre Sprache und unterbrach die Verständigung.'], ['Ergebnis', 'Sie wurden über die Erde zerstreut und hörten auf, die Stadt zu bauen.']], note: 'Die Heilige Schrift nennt Babel und Schinar, gibt aber weder Maße oder Form noch moderne Koordinaten für den Turm an.' },
    known: ['Grade der Gewissheit', 'Was erkennbar ist und was offenbleibt', 'Der antike Kontext hilft, wenn der historische Ort, bekannte Architektur und das in der Schrift erzählte Ereignis klar voneinander unterschieden werden.'],
    certainty: [['Weitgehend anerkannter Kontext', 'Babel, Babylon und Schinar', 'Babel wird traditionell mit Babylon in der Ebene Untermesopotamiens verbunden. Die Ruinen der historischen Stadt liegen im heutigen Irak.'], ['Nicht nachgewiesene Zuordnung', 'Der konkrete Turm des Berichts', 'Babylon besaß große Zikkurate, darunter Etemenanki; die Archäologie weist jedoch kein erhaltenes Bauwerk als den genauen Turm aus 1. Mose 11 nach.']],
    views: ['Drei ergänzende Blickwinkel', 'Wie Bericht und Kontext zu lesen sind', 'Diese Blickwinkel konkurrieren nicht um den Standort des Turms: Sie beantworten verschiedene Fragen und verlangen unterschiedliche Grade der Gewissheit.'], expand: 'Bild vergrößern', proposal: 'Was der Blickwinkel beiträgt', explain: 'Welche Einzelheiten er verständlich macht', difficulty: 'Welche Grenze bestehen bleibt',
    theories: [
      { title: 'Theologische Lesart des Berichts', body: 'Sie stellt Gottes Souveränität dem menschlichen Vorhaben gegenüber, sich zu sammeln, sich einen Namen zu machen und Zerstreuung zu vermeiden.', support: 'Das erklärte Motiv der Bauleute, Gottes Handeln und der Ausgang des Berichts.', limit: 'Die theologische Auslegung bestimmt weder die materielle Form noch den genauen Standort des Turms.', source: 'Weiterführende Quellen:', sourceLinks: ['Quelle 5', 'Quelle 6'], caption: 'Konzeptionelle Illustration menschlichen Strebens, göttlichen Eingreifens und der Zerstreuung. Sie ist keine archäologische Rekonstruktion.', alt: 'Illustration im Pergamentstil mit einer unvollendeten Stadt und einem Turm unter himmlischem Licht, während Menschengruppen in verschiedene Richtungen ziehen.', aria: 'Theologische Illustration von Babel und der Zerstreuung vergrößern' },
      { title: 'Babylon in der mesopotamischen Ebene', body: 'Dieser Blickwinkel ordnet den historischen Rahmen Babylon zu, einer antiken Stadt am Euphrat in der weiten Schwemmebene Untermesopotamiens.', support: 'Babylons archäologischer Standort, seine Flusslandschaft und seine lange städtische Tradition.', limit: 'Die Zuordnung zu Babylon identifiziert nicht automatisch das Gebäude und datiert nicht das Ereignis aus 1. Mose 11.', source: 'Weiterführende Quellen:', sourceLinks: ['Quelle 1', 'Quelle 2'], caption: 'Konzeptionelle Illustration Babylons und seiner Flussebene. Sie ist weder ein archäologischer Plan noch ein sicherer Standort des Turms.', alt: 'Konzeptionelle Pergamentansicht einer Lehmziegelstadt am Euphrat, umgeben von Kanälen, Feldern und Palmen.', aria: 'Illustration Babylons in der mesopotamischen Ebene vergrößern' },
      { title: 'Zikkurate und Etemenanki', body: 'Zikkurate zeigen, wie mesopotamische Städte große gestufte Plattformen für ihre Tempel errichteten. Etemenanki war der große Zikkurat Babylons.', support: 'Archäologische Reste, königliche Inschriften und Vergleiche mit anderen mesopotamischen Zikkuraten.', limit: 'Kulturelle oder architektonische Ähnlichkeit liefert Kontext; sie beweist nicht, dass Etemenanki der genaue Turm der Heiligen Schrift ist.', source: 'Weiterführende Quellen:', sourceLinks: ['Quelle 2', 'Quelle 3', 'Quelle 4'], caption: 'Konzeptionelle visuelle Rekonstruktion eines mesopotamischen Zikkurats im Bau. Sie weist ihn nicht nachgewiesen als Turm zu Babel aus.', alt: 'Illustration im Pergamentstil eines großen Lehmziegel-Zikkurats im Bau mit Rampen, Gerüsten und Arbeitern.', aria: 'Konzeptionelle Rekonstruktion eines mesopotamischen Zikkurats vergrößern' }
    ],
    comparison: ['Vergleich der Blickwinkel', 'Was jeder Ansatz beantwortet und offenlässt'], comparisonLabel: 'Vergleichstabelle zur Babel-Studie', headers: ['Ansatz', 'Anhaltspunkt', 'Hauptbeitrag', 'Grenze'], rows: [['Theologische Lesart', 'Ablauf und ausgedrückte Motive in 1. Mose 11.', 'Lenkt den Blick auf Gott, menschliche Absicht und Zerstreuung.', 'Rekonstruiert kein historisches Gebäude.'], ['Kontext Babylons', 'Die historische Stadt und ihre Landschaft in Untermesopotamien.', 'Bietet einen plausiblen geografischen und städtischen Rahmen für Schinar und Babel.', 'Beweist weder genaues Datum noch genauen Ort des Ereignisses.'], ['Kontext der Zikkurate', 'Mesopotamische Architektur, Reste und Inschriften.', 'Erklärt die Art monumentaler Bauwerke, die in der Region bekannt war.', 'Etemenanki ist möglicher Hintergrund, keine nachgewiesene Zuordnung.']],
    method: ['Kriterium:', 'Die Heilige Schrift, der archäologische Ort und die Deutungsvorschläge werden als unterschiedliche Ebenen der Evidenz dargestellt.'],
    conclusion: ['Was du jetzt erkennen kannst', 'Was der Kontext zum Babel-Bericht beiträgt', 'Babel gehört zu einer städtischen mesopotamischen Welt, in der Städte, Ziegel und gestufte Bauwerke konkrete Wirklichkeiten waren. Dieser Kontext macht die Szene verständlicher, erlaubt aber nicht, auf eine Ruine zu zeigen und sie zum genauen Turm aus 1. Mose 11 zu erklären.', 'Im Zentrum des Berichts bleiben Gottes Handeln und der Ausgang des menschlichen Vorhabens. Die Archäologie erhellt den Schauplatz; die Heilige Schrift bestimmt die Botschaft der Studie.'],
    reflection: { heading: ['Kehre zur Heiligen Schrift zurück', 'Was bringt das für meine Lektüre?'], answerLabel: 'Eine Orientierung anzeigen', items: [['1. Unterscheide Motiv und Auslegung', 'Welche Motive schreibt 1. Mose 11,4 den Bauleuten ausdrücklich zu, und welche Bewertung fügen wir bei der Auslegung hinzu?', 'Der Vers nennt den Wunsch, sich einen Namen zu machen und Zerstreuung zu vermeiden. Stolz, Selbstgenügsamkeit oder Widerstand gegen Gottes Absicht darin zu sehen, ist eine theologische Auslegung, die zum Ablauf passt, aber von den ausdrücklichen Worten des Abschnitts unterschieden werden sollte.'], ['2. Sieh auf den Ausgang', 'Wie antwortet Gott auf das Vorhaben, und was verändert sich im Leben der Bauleute?', 'Gott verwirrt ihre Sprache, unterbricht die Verständigung und zerstreut sie. Die Stadt bleibt unvollendet, und an die Stelle der gesuchten Konzentration tritt die Verteilung der Völker.']], link: 'Zu 1. Mose 11,1–9 zurückkehren', takeaway: ['Ergebnis des Weges:', 'Du kannst jetzt die zentrale Botschaft des Berichts erkennen, ihn vorsichtig in die mesopotamische Welt einordnen und vermeiden, einen bekannten Zikkurat als nachgewiesenen Turm auszugeben.'] },
    glossary: ['Schlüsselbegriffe', 'Kurzes Glossar'], glossaryEntries: [['Babel', 'Name der Stadt in 1. Mose 11, im Bericht mit der Verwirrung der Sprachen verbunden.'], ['Schinar', 'Biblische Region, die gewöhnlich mit Babylonien und Untermesopotamien verbunden wird.'], ['Babylon', 'Antike mesopotamische Stadt am Euphrat im heutigen Irak.'], ['Zikkurat', 'Mesopotamisches Bauwerk aus gestuften Terrassen, das zu einem Tempelkomplex gehörte.'], ['Etemenanki', 'Großer, Marduk geweihter Zikkurat Babylons; er liefert historischen Kontext, ist aber keine nachgewiesene Zuordnung des biblischen Turms.']],
    editorial: ['Redaktionelle Angaben', 'Umfang und Prüfung'], editorialEntries: [['Verantwortlich', 'Jose A Bejarano V'], ['Version', '0.1 · zweiter dreisprachiger interner Pilot'], ['Letzte Prüfung', '20. September 2026'], ['Methode', 'Geführte Lektüre, die die Heilige Schrift, den historisch-archäologischen Kontext und theologische Auslegungen unterscheidet.']], ai: ['Zu den Bildern:', 'Die mit künstlicher Intelligenz erzeugten konzeptionellen Illustrationen dienen als visuelle Hilfe. Sie sind keine historischen, archäologischen oder geografischen Belege.'],
    sources: ['Quellen zum Weiterstudieren', 'Herangezogene Literatur'], sourceNotes: ['institutioneller Eintrag und archäologische Daten zu Babylon.', 'institutioneller Überblick über Etemenanki und seine Reste.', 'museale Einführung in die Architektur der Zikkurate.', 'Inschrift Nebukadnezars II. zum Wiederaufbau Etemenankis.', 'Studie zum babylonischen Hintergrund der Sprache in 1. Mose 11.', 'rhetorische Analyse von Einheit, Zerstreuung und Schöpfungsordnung.'], close: 'Vergrößertes Bild schließen'
  }
};
