export const edenCopy = {
  es: {
    metaTitle: 'Los cuatro ríos del Edén: del texto sagrado al mapa | Horizonte 55', metaDescription: 'Recorrido guiado de Génesis 2 para distinguir el texto sagrado de las reconstrucciones geográficas sobre los cuatro ríos del Edén.',
    hero: ['Contexto bíblico · Piloto editorial en español', 'Los cuatro ríos del Edén: del texto sagrado al mapa', 'Génesis nombra cuatro ríos. ¿Por qué, entonces, encontramos mapas diferentes del Edén? Vamos a observar el pasaje y comparar qué explica cada propuesta.', 'Al terminar:', 'podrás distinguir lo que dice el texto sagrado de lo que añade una reconstrucción geográfica.', 'Leer Génesis 2:10–14', 'Volver al capítulo'],
    factsLabel: 'Ficha del estudio', facts: [['Pasaje', 'Génesis 2:10–14'], ['Pregunta central', '¿Qué puede afirmarse y qué permanece abierto sobre los cuatro ríos?'], ['Lectura estimada', '8–10 minutos'], ['Estado', 'Piloto interno · versión 0.3']],
    faith: ['Criterio del estudio', 'La Escritura es el fundamento', 'Horizonte 55 recibe el texto sagrado como fundamento de este estudio. Las ubicaciones geográficas que se presentan a continuación son propuestas humanas para comprender el pasaje; no modifican ni niegan lo afirmado por las Escrituras.'],
    observation: { heading: ['Primero, mira el texto sagrado', 'Observa antes de mirar los mapas'], prompt: 'Lee Génesis 2:10–14 e identifica los cuatro ríos. ¿Con qué territorios los relaciona el pasaje?', answerLabel: 'Comparar con una observación guiada', tableLabel: 'Relaciones geográficas mencionadas en Génesis 2', headers: ['Río', 'Información que proporciona el pasaje'], rows: [['Pisón', 'Rodea la tierra de Havila.'], ['Gihón', 'Rodea la tierra de Cus.'], ['Hidekel', 'Se relaciona con la región de Asiria.'], ['Éufrates', 'Se menciona por su nombre.']], note: 'El texto sagrado también describe la relación entre el río que riega el huerto y los cuatro brazos que aparecen después.' },
    known: ['Grados de certeza', 'Qué puede reconocerse y qué permanece abierto', 'Para dibujar un mapa necesitamos identificar los lugares y explicar cómo se relacionan los cursos de agua. Reconocer dos nombres no resuelve por sí solo todo el recorrido.'],
    certainty: [
      ['Identificación ampliamente reconocida', 'Hidekel y Éufrates', 'Hidekel suele identificarse con el Tigris y Éufrates conserva su nombre histórico. Ambos sitúan parte del marco narrativo en relación con Mesopotamia.'],
      ['Identificación debatida', 'Pisón, Gihón, Havila y Cus', 'No existe una identificación geográfica aceptada de manera general que permita reconstruir un único mapa con certeza.']
    ],
    views: ['Tres familias de interpretación', 'Cómo se ha intentado comprender la geografía', 'Mientras comparas las propuestas, observa qué elementos proceden del pasaje y cuáles añade cada reconstrucción.'],
    expand: 'Ampliar imagen', proposal: 'Qué propone', explain: 'Qué detalles intenta explicar', difficulty: 'Qué deja pendiente',
    theories: [
      { title: 'Geografía teológica o simbólica', body: 'Lee los cuatro ríos como una imagen de Edén como fuente de vida. Su propósito principal es interpretar el significado del relato, no reconstruir un punto geográfico.', support: 'La amplitud geográfica y la función literaria de los cuatro brazos.', limit: 'La lectura simbólica no resuelve si el relato conserva también referencias a territorios reales.', source: 'Lecturas relacionadas:', sourceLinks: ['fuente 4', 'fuente 5'], caption: 'Ilustración conceptual de Edén como fuente de vida, con el río dividido en cuatro ramas. No representa un mapa geográfico comprobado.', alt: 'Ilustración conceptual en estilo de pergamino de un paraíso exuberante y luminoso del que un río se divide claramente en cuatro ramas.', aria: 'Ampliar ilustración del paraíso y sus cuatro ramas' },
      { title: 'Cabeceras del norte de Mesopotamia', body: 'Relaciona el escenario con las regiones montañosas donde nacen el Tigris y el Éufrates.', support: 'La proximidad de las cabeceras de los dos ríos conocidos.', limit: 'No identifica con seguridad Pisón y Gihón ni reproduce claramente un río que se divide en cuatro brazos.', source: 'Lectura relacionada:', sourceLinks: ['fuente 1'], caption: 'Ilustración conceptual de esta hipótesis. No representa una ubicación comprobada del Edén.', alt: 'Ilustración conceptual en estilo de pergamino de montañas y cursos fluviales en el norte de Mesopotamia.', aria: 'Ampliar ilustración de las cabeceras del norte de Mesopotamia' },
      { title: 'Baja Mesopotamia y cuenca del Golfo Pérsico', body: 'Considera antiguos cauces de Arabia y una cuenca del Golfo expuesta cuando el nivel del mar era menor.', support: 'La existencia de sistemas fluviales y paleocauces hoy transformados o sumergidos.', limit: 'La paleohidrología demuestra paisajes antiguos, pero por sí sola no identifica esos cauces con los cuatro ríos de Génesis.', source: 'Lecturas relacionadas:', sourceLinks: ['fuente 2', 'fuente 3'], caption: 'Ilustración conceptual de un paisaje antiguo con cauces y humedales. No identifica esos cursos de agua con certeza bíblica.', alt: 'Ilustración conceptual en estilo de pergamino de una antigua cuenca baja con ríos, humedales y un paleocauce.', aria: 'Ampliar ilustración de la baja Mesopotamia y la cuenca del Golfo Pérsico' }
    ],
    comparison: ['Comparación de propuestas', 'Qué aporta y qué no resuelve cada lectura'], comparisonLabel: 'Tabla comparativa de las tres interpretaciones',
    headers: ['Propuesta', 'Punto de apoyo', 'Pregunta que permanece', 'Cómo debe leerse'],
    rows: [
      ['Lectura teológica', 'Función del Edén y de sus aguas dentro del relato.', 'Si el texto sagrado conserva además referencias a una geografía reconstruible.', 'Interpretación literaria y teológica.'],
      ['Cabeceras del norte', 'Origen montañoso del Tigris y del Éufrates.', 'Identidad de Pisón y Gihón y sentido de la división en cuatro brazos.', 'Reconstrucción geográfica posible.'],
      ['Cuenca del Golfo', 'Paleocauces de Arabia y transformaciones antiguas de la cuenca.', 'Correspondencia directa entre esos cauces y los cuatro nombres de Génesis.', 'Hipótesis geográfica apoyada en un paisaje antiguo.']
    ],
    method: ['Criterio:', 'esta comparación describe lo que cada propuesta intenta explicar; no establece cuál identifica la ubicación del Edén.'],
    conclusion: ['Lo que ya puedes reconocer', 'Qué aprendiste al comparar los mapas', 'Ahora sabemos por qué existen mapas diferentes: cada propuesta intenta completar datos que el pasaje no convierte en coordenadas modernas. El Tigris y el Éufrates ofrecen referencias importantes, pero no bastan para reconstruir con certeza todo el sistema descrito.', 'Un mapa puede ayudarnos a pensar el contexto; su ubicación exacta del Edén sigue siendo una reconstrucción humana y debe presentarse como tal.'],
    reflection: { heading: ['Regresa al pasaje', '¿Qué aporta esto a mi lectura?'], answerLabel: 'Ver una respuesta orientativa', items: [['1. Lee un mapa con criterio', 'Si un mapa señala un punto exacto como «Edén», ¿ese punto aparece identificado así en el pasaje o es una propuesta de quien elaboró el mapa?', 'El pasaje describe el río y nombra lugares relacionados, pero no ofrece una coordenada moderna del Edén. El punto exacto dibujado en un mapa pertenece a la reconstrucción de su autor y debe evaluarse por sus argumentos y límites.'], ['2. Vuelve al huerto', 'Lee ahora Génesis 2:8–15. Observa qué prepara Dios y qué tarea recibe el ser humano. ¿Cómo encaja el río en esa escena?', 'El relato presenta el huerto, el agua y los árboles como parte del entorno que Dios prepara. Después coloca allí al ser humano con la tarea de cultivarlo y cuidarlo. El río forma parte de esa escena de provisión y responsabilidad.']], link: 'Volver a Génesis 2:8–15', takeaway: ['Resultado del recorrido:', 'no hemos encontrado una ubicación comprobada del Edén; hemos aprendido a leer sus mapas con criterio y a reconocer mejor la función del río dentro del relato.'] },
    glossary: ['Palabras clave', 'Glosario breve'], glossaryEntries: [['Edén', 'Región mencionada en Génesis donde Dios plantó el huerto.'], ['Pisón y Gihón', 'Dos de los cuatro brazos nombrados en el pasaje; su identificación geográfica permanece debatida.'], ['Hidekel', 'Nombre bíblico asociado de manera habitual con el río Tigris.'], ['Havila y Cus', 'Territorios vinculados por el relato con Pisón y Gihón; sus referencias geográficas se interpretan de distintas maneras.'], ['Paleocauce', 'Huella o recorrido antiguo de un curso de agua que cambió o dejó de fluir.']],
    editorial: ['Ficha editorial', 'Alcance y revisión'], editorialEntries: [['Responsable', 'Jose A Bejarano V'], ['Versión', '0.3 · piloto interno trilingüe'], ['Última revisión', '20 de septiembre de 2026'], ['Método', 'Lectura comparativa que separa el contenido del pasaje, las identificaciones generalmente reconocidas y las reconstrucciones debatidas.']],
    ai: ['Sobre las imágenes:', 'las ilustraciones conceptuales generadas con inteligencia artificial sirven como apoyo visual. No constituyen evidencia histórica, arqueológica o geográfica.'],
    sources: ['Fuentes para continuar', 'Lecturas consultadas'], sourceNotes: ['panorama de las identificaciones y sus límites.', 'síntesis paleoambiental y arqueológica de la cuenca del Golfo.', 'propuesta que relaciona un paleocauce de Arabia con Pisón.', 'lectura literaria de la geografía del relato.', 'discusión académica de la interpretación cosmológica.'], close: 'Cerrar imagen ampliada'
  },
  en: {
    metaTitle: 'The four rivers of Eden: from sacred text to map | Horizonte 55', metaDescription: 'A guided journey through Genesis 2 that distinguishes the sacred text from geographical reconstructions of the four rivers of Eden.',
    hero: ['Biblical context · Editorial pilot in English', 'The four rivers of Eden: from sacred text to map', 'Genesis names four rivers. Why, then, do we find different maps of Eden? We will observe the passage and compare what each proposal explains.', 'By the end:', 'you will be able to distinguish what the sacred text says from what a geographical reconstruction adds.', 'Read Genesis 2:10–14', 'Return to the chapter'],
    factsLabel: 'Study overview', facts: [['Passage', 'Genesis 2:10–14'], ['Central question', 'What can be affirmed, and what remains open, about the four rivers?'], ['Estimated reading time', '8–10 minutes'], ['Status', 'Internal pilot · version 0.3']],
    faith: ['Study criterion', 'Scripture is the foundation', 'Horizonte 55 receives the sacred text as the foundation of this study. The geographical locations presented below are human proposals for understanding the passage; they do not alter or deny what Scripture affirms.'],
    observation: { heading: ['First, look at the sacred text', 'Observe before looking at the maps'], prompt: 'Read Genesis 2:10–14 and identify the four rivers. Which territories does the passage associate with them?', answerLabel: 'Compare with a guided observation', tableLabel: 'Geographical relationships mentioned in Genesis 2', headers: ['River', 'Information provided by the passage'], rows: [['Pishon', 'It flows around the land of Havilah.'], ['Gihon', 'It flows around the land of Cush.'], ['Hiddekel', 'It is associated with the region of Assyria.'], ['Euphrates', 'It is mentioned by name.']], note: 'The sacred text also describes the relationship between the river that waters the garden and the four branches that appear afterward.' },
    known: ['Degrees of certainty', 'What can be recognized and what remains open', 'To draw a map, we need to identify the places and explain how the waterways relate to one another. Recognizing two names does not by itself resolve the whole course.'],
    certainty: [['Widely recognized identification', 'Hiddekel and Euphrates', 'Hiddekel is commonly identified with the Tigris, while the Euphrates retains its historical name. Together they place part of the narrative setting in relation to Mesopotamia.'], ['Debated identification', 'Pishon, Gihon, Havilah and Cush', 'There is no generally accepted geographical identification that makes it possible to reconstruct one map with certainty.']],
    views: ['Three families of interpretation', 'How the geography has been understood', 'As you compare the proposals, notice which elements come from the passage and which are added by each reconstruction.'], expand: 'Enlarge image', proposal: 'What it proposes', explain: 'Which details it seeks to explain', difficulty: 'What it leaves unresolved',
    theories: [
      { title: 'Theological or symbolic geography', body: 'This view reads the four rivers as an image of Eden as a source of life. Its main purpose is to interpret the meaning of the account, rather than reconstruct a geographical point.', support: 'The geographical breadth and literary function of the four branches.', limit: 'A symbolic reading does not resolve whether the account also preserves references to real territories.', source: 'Related readings:', sourceLinks: ['source 4', 'source 5'], caption: 'Conceptual illustration of Eden as a source of life, with the river divided into four branches. It does not represent a proven geographical map.', alt: 'Conceptual parchment-style illustration of a magnificent, luminous paradise from which one river clearly divides into four branches.', aria: 'Enlarge illustration of paradise and its four branches' },
      { title: 'Headwaters of northern Mesopotamia', body: 'This view relates the setting to the mountainous regions where the Tigris and Euphrates rise.', support: 'The proximity of the headwaters of the two known rivers.', limit: 'It does not identify Pishon and Gihon securely or clearly reproduce one river dividing into four branches.', source: 'Related reading:', sourceLinks: ['source 1'], caption: 'Conceptual illustration of this hypothesis. It does not represent a proven location of Eden.', alt: 'Conceptual parchment-style illustration of mountains and waterways in northern Mesopotamia.', aria: 'Enlarge illustration of the headwaters of northern Mesopotamia' },
      { title: 'Lower Mesopotamia and the Persian Gulf basin', body: 'This view considers ancient channels in Arabia and a Gulf basin exposed when sea level was lower.', support: 'The existence of river systems and paleochannels that are now transformed or submerged.', limit: 'Paleohydrology demonstrates ancient landscapes, but by itself it does not identify those channels with the four rivers of Genesis.', source: 'Related readings:', sourceLinks: ['source 2', 'source 3'], caption: 'Conceptual illustration of an ancient landscape with channels and wetlands. It does not identify those waterways with biblical certainty.', alt: 'Conceptual parchment-style illustration of an ancient lowland basin with rivers, wetlands and a paleochannel.', aria: 'Enlarge illustration of Lower Mesopotamia and the Persian Gulf basin' }
    ],
    comparison: ['Comparison of proposals', 'What each reading contributes and leaves unresolved'], comparisonLabel: 'Comparison table of the three interpretations', headers: ['Proposal', 'Supporting point', 'Question that remains', 'How it should be read'],
    rows: [['Theological reading', 'The function of Eden and its waters within the account.', 'Whether the sacred text also preserves references to reconstructable geography.', 'A literary and theological interpretation.'], ['Northern headwaters', 'Mountain sources of the Tigris and Euphrates.', 'The identity of Pishon and Gihon and the meaning of the division into four branches.', 'A possible geographical reconstruction.'], ['Gulf basin', 'Arabian paleochannels and ancient transformations of the basin.', 'A direct correspondence between those channels and the four names in Genesis.', 'A geographical hypothesis supported by an ancient landscape.']],
    method: ['Criterion:', 'this comparison describes what each proposal seeks to explain; it does not establish which one identifies Eden’s location.'],
    conclusion: ['What you can now recognize', 'What you learned by comparing the maps', 'We now know why different maps exist: each proposal attempts to complete information that the passage does not turn into modern coordinates. The Tigris and Euphrates provide important references, but they are not enough to reconstruct the entire system with certainty.', 'A map can help us think about the context; its exact location for Eden remains a human reconstruction and should be presented as such.'],
    reflection: { heading: ['Return to the passage', 'What does this add to my reading?'], answerLabel: 'See a guided answer', items: [['1. Read a map critically', 'If a map marks an exact point as “Eden,” is that point identified that way in the passage, or is it a proposal made by the mapmaker?', 'The passage describes the river and names related places, but it gives no modern coordinate for Eden. The exact point drawn on a map belongs to its author’s reconstruction and should be evaluated by its arguments and limits.'], ['2. Return to the garden', 'Now read Genesis 2:8–15. Notice what God prepares and what task the human being receives. How does the river fit into that scene?', 'The account presents the garden, water and trees as part of the environment God prepares. God then places the human being there with the task of working and caring for it. The river belongs to this scene of provision and responsibility.']], link: 'Return to Genesis 2:8–15', takeaway: ['Result of the journey:', 'we have not found a proven location of Eden; we have learned to read its maps critically and to recognize more clearly the river’s function within the account.'] },
    glossary: ['Key terms', 'Brief glossary'], glossaryEntries: [['Eden', 'The region in Genesis where God planted the garden.'], ['Pishon and Gihon', 'Two of the four branches named in the passage; their geographical identification remains debated.'], ['Hiddekel', 'The biblical name commonly associated with the Tigris River.'], ['Havilah and Cush', 'Territories linked in the account with Pishon and Gihon; their geographical references are interpreted in different ways.'], ['Paleochannel', 'The trace or former course of a waterway that changed or ceased to flow.']],
    editorial: ['Editorial record', 'Scope and review'], editorialEntries: [['Responsible person', 'Jose A Bejarano V'], ['Version', '0.3 · trilingual internal pilot'], ['Last reviewed', '20 September 2026'], ['Method', 'A comparative reading that separates the content of the passage, generally recognized identifications and debated reconstructions.']], ai: ['About the images:', 'the conceptual illustrations generated with artificial intelligence serve as visual support. They are not historical, archaeological or geographical evidence.'],
    sources: ['Sources for further study', 'Works consulted'], sourceNotes: ['overview of proposed identifications and their limits.', 'paleoenvironmental and archaeological synthesis of the Gulf basin.', 'proposal connecting an Arabian paleochannel with Pishon.', 'literary reading of the account’s geography.', 'academic discussion of the cosmological interpretation.'], close: 'Close enlarged image'
  },
  de: {
    metaTitle: 'Die vier Flüsse Edens: von der Heiligen Schrift zur Karte | Horizonte 55', metaDescription: 'Ein geführter Weg durch 1. Mose 2, der die Heilige Schrift von geografischen Rekonstruktionen der vier Flüsse Edens unterscheidet.',
    hero: ['Biblischer Kontext · Redaktioneller Pilot auf Deutsch', 'Die vier Flüsse Edens: von der Heiligen Schrift zur Karte', 'Genesis nennt vier Flüsse. Warum finden wir dann unterschiedliche Karten von Eden? Wir betrachten den Abschnitt und vergleichen, was jeder Vorschlag erklärt.', 'Am Ende:', 'kannst du unterscheiden, was die Heilige Schrift sagt und was eine geografische Rekonstruktion hinzufügt.', '1. Mose 2,10–14 lesen', 'Zum Kapitel zurückkehren'],
    factsLabel: 'Übersicht zur Studie', facts: [['Bibelstelle', '1. Mose 2,10–14'], ['Leitfrage', 'Was lässt sich über die vier Flüsse sagen, und was bleibt offen?'], ['Geschätzte Lesezeit', '8–10 Minuten'], ['Status', 'Interner Pilot · Version 0.3']],
    faith: ['Maßstab der Studie', 'Die Heilige Schrift ist die Grundlage', 'Horizonte 55 nimmt die Heilige Schrift als Grundlage dieser Studie. Die nachfolgend vorgestellten geografischen Verortungen sind menschliche Vorschläge zum Verständnis des Abschnitts; sie verändern oder verneinen nicht, was die Heilige Schrift aussagt.'],
    observation: { heading: ['Sieh zuerst auf die Heilige Schrift', 'Lies die Heilige Schrift, bevor du die Karten ansiehst'], prompt: 'Lies 1. Mose 2,10–14 und bestimme die vier Flüsse. Mit welchen Gebieten verbindet der Abschnitt sie?', answerLabel: 'Mit einer geführten Beobachtung vergleichen', tableLabel: 'In 1. Mose 2 genannte geografische Beziehungen', headers: ['Fluss', 'Angabe im Abschnitt'], rows: [['Pison', 'Er umfließt das Land Chavila.'], ['Gichon', 'Er umfließt das Land Kusch.'], ['Hiddekel', 'Er wird mit der Region Assur verbunden.'], ['Euphrat', 'Er wird namentlich genannt.']], note: 'Die Heilige Schrift beschreibt außerdem die Beziehung zwischen dem Strom, der den Garten bewässert, und den vier Hauptarmen, die danach erscheinen.' },
    known: ['Grade der Gewissheit', 'Was erkennbar ist und was offenbleibt', 'Um eine Karte zu zeichnen, müssen wir die Orte bestimmen und erklären, wie die Wasserläufe zusammenhängen. Zwei Namen zu erkennen, klärt den gesamten Verlauf noch nicht.'], certainty: [['Weitgehend anerkannte Zuordnung', 'Hiddekel und Euphrat', 'Hiddekel wird gewöhnlich mit dem Tigris identifiziert; der Euphrat trägt weiterhin seinen historischen Namen. Beide verbinden einen Teil des erzählerischen Rahmens mit Mesopotamien.'], ['Umstrittene Zuordnung', 'Pison, Gichon, Chavila und Kusch', 'Es gibt keine allgemein anerkannte geografische Zuordnung, aus der sich mit Sicherheit eine einzige Karte rekonstruieren ließe.']],
    views: ['Drei Gruppen von Deutungen', 'Wie die Geografie verstanden wurde', 'Achte beim Vergleich darauf, welche Elemente aus dem Abschnitt stammen und welche jede Rekonstruktion hinzufügt.'], expand: 'Bild vergrößern', proposal: 'Was sie vorschlägt', explain: 'Welche Einzelheiten sie erklären möchte', difficulty: 'Was offenbleibt',
    theories: [
      { title: 'Theologische oder symbolische Geografie', body: 'Diese Deutung liest die vier Flüsse als Bild für Eden als Quelle des Lebens. Ihr Hauptzweck ist, die Bedeutung des Berichts zu deuten, nicht einen geografischen Punkt zu rekonstruieren.', support: 'Die geografische Weite und die literarische Funktion der vier Hauptarme.', limit: 'Eine symbolische Lesart klärt nicht, ob der Bericht zugleich Hinweise auf reale Gebiete bewahrt.', source: 'Weiterführende Quellen:', sourceLinks: ['Quelle 4', 'Quelle 5'], caption: 'Konzeptionelle Illustration Edens als Quelle des Lebens, wobei sich der Strom in vier Hauptarme teilt. Sie stellt keine nachgewiesene geografische Karte dar.', alt: 'Konzeptionelle Illustration im Pergamentstil eines prachtvollen, lichtvollen Paradieses, aus dem sich ein Strom deutlich in vier Hauptarme teilt.', aria: 'Illustration des Paradieses und seiner vier Hauptarme vergrößern' },
      { title: 'Quellgebiete im Norden Mesopotamiens', body: 'Diese Deutung verbindet den Schauplatz mit den Bergregionen, in denen Tigris und Euphrat entspringen.', support: 'Die Nähe der Quellgebiete der beiden bekannten Flüsse.', limit: 'Sie identifiziert Pison und Gichon nicht sicher und bildet nicht eindeutig einen Strom ab, der sich in vier Hauptarme teilt.', source: 'Weiterführende Quelle:', sourceLinks: ['Quelle 1'], caption: 'Konzeptionelle Illustration dieser Hypothese. Sie zeigt keinen nachgewiesenen Ort Edens.', alt: 'Konzeptionelle Illustration im Pergamentstil mit Bergen und Wasserläufen im Norden Mesopotamiens.', aria: 'Illustration der Quellgebiete im Norden Mesopotamiens vergrößern' },
      { title: 'Untermesopotamien und das Becken des Persischen Golfs', body: 'Diese Deutung berücksichtigt alte Flussläufe in Arabien und ein Golfbecken, das bei niedrigerem Meeresspiegel freilag.', support: 'Das Vorhandensein von Flusssystemen und Paläoflussbetten, die heute verändert oder überflutet sind.', limit: 'Die Paläohydrologie weist alte Landschaften nach, identifiziert diese Wasserläufe für sich allein jedoch nicht mit den vier Flüssen der Genesis.', source: 'Weiterführende Quellen:', sourceLinks: ['Quelle 2', 'Quelle 3'], caption: 'Konzeptionelle Illustration einer alten Landschaft mit Flussläufen und Feuchtgebieten. Sie ordnet diese Gewässer nicht mit biblischer Gewissheit zu.', alt: 'Konzeptionelle Illustration im Pergamentstil mit einem alten Tieflandbecken, Flüssen, Feuchtgebieten und einem Paläoflussbett.', aria: 'Illustration von Untermesopotamien und dem Becken des Persischen Golfs vergrößern' }
    ],
    comparison: ['Vergleich der Vorschläge', 'Was jede Lesart beiträgt und offenlässt'], comparisonLabel: 'Vergleichstabelle der drei Deutungen', headers: ['Vorschlag', 'Anhaltspunkt', 'Offene Frage', 'So ist er einzuordnen'], rows: [['Theologische Lesart', 'Funktion Edens und seiner Gewässer innerhalb des Berichts.', 'Ob die Heilige Schrift zusätzlich Hinweise auf eine rekonstruierbare Geografie bewahrt.', 'Literarische und theologische Interpretation.'], ['Nördliche Quellgebiete', 'Gebirgsquellen von Tigris und Euphrat.', 'Identität von Pison und Gichon sowie die Bedeutung der Teilung in vier Hauptarme.', 'Mögliche geografische Rekonstruktion.'], ['Golfbecken', 'Paläoflussbetten Arabiens und alte Veränderungen des Beckens.', 'Direkte Entsprechung zwischen diesen Flussläufen und den vier Namen der Genesis.', 'Geografische Hypothese auf Grundlage einer alten Landschaft.']],
    method: ['Kriterium:', 'Dieser Vergleich beschreibt, was jeder Vorschlag zu erklären versucht; er legt nicht fest, welcher davon den Ort Edens bestimmt.'],
    conclusion: ['Was du jetzt erkennen kannst', 'Was du durch den Kartenvergleich gelernt hast', 'Jetzt wissen wir, warum es unterschiedliche Karten gibt: Jeder Vorschlag versucht Angaben zu ergänzen, die der Abschnitt nicht in moderne Koordinaten umsetzt. Tigris und Euphrat liefern wichtige Hinweise, reichen aber nicht aus, um das gesamte beschriebene System sicher zu rekonstruieren.', 'Eine Karte kann helfen, über den Kontext nachzudenken; ihr genauer Ort für Eden bleibt eine menschliche Rekonstruktion und muss als solche dargestellt werden.'],
    reflection: { heading: ['Kehre zum Abschnitt zurück', 'Was bringt das für meine Lektüre?'], answerLabel: 'Eine Orientierung anzeigen', items: [['1. Lies eine Karte mit Urteilskraft', 'Wenn eine Karte einen genauen Punkt als „Eden“ markiert: Wird dieser Punkt im Abschnitt so bestimmt, oder ist er ein Vorschlag des Kartenautors?', 'Der Abschnitt beschreibt den Strom und nennt zugehörige Orte, gibt aber keine moderne Koordinate für Eden an. Der genaue Punkt auf einer Karte gehört zur Rekonstruktion ihres Autors und ist anhand ihrer Argumente und Grenzen zu beurteilen.'], ['2. Kehre zum Garten zurück', 'Lies nun 1. Mose 2,8–15. Achte darauf, was Gott vorbereitet und welche Aufgabe der Mensch erhält. Wie fügt sich der Strom in diese Szene ein?', 'Der Bericht stellt Garten, Wasser und Bäume als Teil der Umgebung dar, die Gott vorbereitet. Danach setzt Gott den Menschen dorthin mit der Aufgabe, den Garten zu bebauen und zu bewahren. Der Strom gehört zu dieser Szene von Versorgung und Verantwortung.']], link: 'Zu 1. Mose 2,8–15 zurückkehren', takeaway: ['Ergebnis des Weges:', 'Wir haben keinen nachgewiesenen Ort Edens gefunden; wir haben gelernt, seine Karten mit Urteilskraft zu lesen und die Funktion des Stroms im Bericht klarer zu erkennen.'] },
    glossary: ['Schlüsselbegriffe', 'Kurzes Glossar'], glossaryEntries: [['Eden', 'Die in Genesis genannte Region, in der Gott den Garten pflanzte.'], ['Pison und Gichon', 'Zwei der vier im Abschnitt genannten Hauptarme; ihre geografische Zuordnung bleibt umstritten.'], ['Hiddekel', 'Der biblische Name, der gewöhnlich mit dem Tigris verbunden wird.'], ['Chavila und Kusch', 'Gebiete, die der Bericht mit Pison und Gichon verbindet; ihre geografischen Bezüge werden unterschiedlich gedeutet.'], ['Paläoflussbett', 'Spur oder früherer Verlauf eines Wasserlaufs, der sich verändert hat oder nicht mehr fließt.']],
    editorial: ['Redaktionelle Angaben', 'Umfang und Prüfung'], editorialEntries: [['Verantwortlich', 'Jose A Bejarano V'], ['Version', '0.3 · dreisprachiger interner Pilot'], ['Letzte Prüfung', '20. September 2026'], ['Methode', 'Vergleichende Lektüre, die den Inhalt des Abschnitts, allgemein anerkannte Zuordnungen und umstrittene Rekonstruktionen voneinander trennt.']], ai: ['Zu den Bildern:', 'Die mit künstlicher Intelligenz erzeugten konzeptionellen Illustrationen dienen als visuelle Hilfe. Sie sind keine historischen, archäologischen oder geografischen Belege.'],
    sources: ['Quellen zum Weiterstudieren', 'Herangezogene Literatur'], sourceNotes: ['Überblick über vorgeschlagene Zuordnungen und ihre Grenzen.', 'paläoökologische und archäologische Synthese zum Golfbecken.', 'Vorschlag, der ein Paläoflussbett in Arabien mit Pison verbindet.', 'literarische Deutung der Geografie des Berichts.', 'wissenschaftliche Diskussion der kosmologischen Interpretation.'], close: 'Vergrößertes Bild schließen'
  }
};
